; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	E:\finalUI_316latest_canuse_300ms_DB_moreliandong\motorTest1\GeneratedFiles\Release\moc_FsmState2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QObject@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_FsmState2@@3Uqt_meta_stringdata_FsmState2_t@@B DD 0ffffffffH ; qt_meta_stringdata_FsmState2
	DD	09H
	DD	00H
	DD	030H
	DD	0ffffffffH
	DD	0dH
	DD	00H
	DD	02aH
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	028H
	DB	'FsmState2', 00H, 'OnpStateTimer', 00H, 00H
	ORG $+3
	ORG $+4
?qt_meta_data_FsmState2@@3QBIB DD 08H			; qt_meta_data_FsmState2
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	013H
	DD	02H
	DD	0aH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@FsmState2@@UBEPBUQMetaObject@@XZ	; FsmState2::metaObject
PUBLIC	?qt_metacast@FsmState2@@UAEPAXPBD@Z		; FsmState2::qt_metacast
PUBLIC	?qt_metacall@FsmState2@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; FsmState2::qt_metacall
PUBLIC	?qt_static_metacall@FsmState2@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; FsmState2::qt_static_metacall
PUBLIC	?staticMetaObject@FsmState2@@2UQMetaObject@@B	; FsmState2::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QObject@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QObject@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?OnpStateTimer@FsmState2@@QAEXXZ:PROC		; FsmState2::OnpStateTimer
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@FsmState2@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@FsmState2@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@FsmState2@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@FsmState2@@2UQMetaObject@@B DB 4 DUP(00H) ; FsmState2::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_FsmState2@@3Uqt_meta_stringdata_FsmState2_t@@B
	DD	FLAT:?qt_meta_data_FsmState2@@3QBIB
	DD	FLAT:?qt_static_metacall@FsmState2@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@FsmState2@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@FsmState2@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'FsmState2::staticMetaObject'', COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_fsmstate2.cpp
; Line 79
	mov	eax, DWORD PTR __imp_?staticMetaObject@QObject@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@FsmState2@@2UQMetaObject@@B, eax
; Line 84
	ret	0
??__E?staticMetaObject@FsmState2@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'FsmState2::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@FsmState2@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@FsmState2@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; FsmState2::qt_static_metacall, COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_fsmstate2.cpp
; Line 66
	push	ebp
	mov	ebp, esp
; Line 67
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN6@qt_static_
; Line 70
	cmp	DWORD PTR __id$[ebp], 0
	jne	SHORT $LN6@qt_static_
; Line 71
	mov	ecx, DWORD PTR __o$[ebp]
; Line 76
	pop	ebp
; Line 71
	jmp	?OnpStateTimer@FsmState2@@QAEXXZ	; FsmState2::OnpStateTimer
$LN6@qt_static_:
; Line 76
	pop	ebp
	ret	0
?qt_static_metacall@FsmState2@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; FsmState2::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@FsmState2@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@FsmState2@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; FsmState2::qt_metacall, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_fsmstate2.cpp
; Line 102
	push	ebp
	mov	ebp, esp
	push	ebx
	push	esi
	push	edi
; Line 103
	push	DWORD PTR __a$[ebp]
	mov	edi, DWORD PTR __c$[ebp]
	mov	ebx, ecx
	push	DWORD PTR __id$[ebp]
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QObject@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 104
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 106
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 107
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 108
	test	esi, esi
	jne	SHORT $LN7@qt_metacal
	mov	ecx, ebx
	call	?OnpStateTimer@FsmState2@@QAEXXZ	; FsmState2::OnpStateTimer
; Line 113
	dec	esi
	pop	edi
; Line 115
	mov	eax, esi
	pop	esi
	pop	ebx
; Line 116
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 110
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 111
	cmp	esi, 1
	jge	SHORT $LN7@qt_metacal
; Line 112
	mov	eax, DWORD PTR __a$[ebp]
	mov	eax, DWORD PTR [eax]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 113
	dec	esi
$LN6@qt_metacal:
; Line 115
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
	pop	esi
	pop	ebx
; Line 116
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@FsmState2@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; FsmState2::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@FsmState2@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@FsmState2@@UAEPAXPBD@Z PROC		; FsmState2::qt_metacast, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_fsmstate2.cpp
; Line 94
	push	ebp
	mov	ebp, esp
	push	esi
; Line 95
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
	pop	esi
; Line 99
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 96
	mov	eax, OFFSET ?qt_meta_stringdata_FsmState2@@3Uqt_meta_stringdata_FsmState2_t@@B+48
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 97
	mov	eax, edi
	pop	edi
	pop	esi
; Line 99
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 98
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QObject@@UAEPAXPBD@Z
	pop	edi
	pop	esi
; Line 99
	pop	ebp
	ret	4
?qt_metacast@FsmState2@@UAEPAXPBD@Z ENDP		; FsmState2::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@FsmState2@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@FsmState2@@UBEPBUQMetaObject@@XZ PROC	; FsmState2::metaObject, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_fsmstate2.cpp
; Line 90
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@FsmState2@@2UQMetaObject@@B ; FsmState2::staticMetaObject
; Line 91
	ret	0
?metaObject@FsmState2@@UBEPBUQMetaObject@@XZ ENDP	; FsmState2::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File d:\qtlatest\5.12.0\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
