; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	E:\finalUI_316latest_canuse_300ms_DB_moreliandong\motorTest1\GeneratedFiles\Release\moc_frmLogin.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

EXTRN	__imp_?staticMetaObject@QDialog@@2UQMetaObject@@B:BYTE
CONST	SEGMENT
?qt_meta_stringdata_frmLogin@@3Uqt_meta_stringdata_frmLogin_t@@B DD 0ffffffffH ; qt_meta_stringdata_frmLogin
	DD	08H
	DD	00H
	DD	040H
	DD	0ffffffffH
	DD	0aH
	DD	00H
	DD	039H
	DD	0ffffffffH
	DD	00H
	DD	00H
	DD	034H
	DD	0ffffffffH
	DD	09H
	DD	00H
	DD	025H
	DB	'frmLogin', 00H, 'OnbtnLogin', 00H, 00H, 'OnbtnExit', 00H
	ORG $+1
?qt_meta_data_frmLogin@@3QBIB DD 08H			; qt_meta_data_frmLogin
	DD	00H
	DD	00H
	DD	00H
	DD	02H
	DD	0eH
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	01H
	DD	00H
	DD	018H
	DD	02H
	DD	08H
	DD	03H
	DD	00H
	DD	019H
	DD	02H
	DD	08H
	DD	02bH
	DD	02bH
	DD	00H
CONST	ENDS
PUBLIC	?metaObject@frmLogin@@UBEPBUQMetaObject@@XZ	; frmLogin::metaObject
PUBLIC	?qt_metacast@frmLogin@@UAEPAXPBD@Z		; frmLogin::qt_metacast
PUBLIC	?qt_metacall@frmLogin@@UAEHW4Call@QMetaObject@@HPAPAX@Z ; frmLogin::qt_metacall
PUBLIC	?qt_static_metacall@frmLogin@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ; frmLogin::qt_static_metacall
PUBLIC	?staticMetaObject@frmLogin@@2UQMetaObject@@B	; frmLogin::staticMetaObject
EXTRN	__imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ:PROC
EXTRN	__imp_?qt_metacast@QDialog@@UAEPAXPBD@Z:PROC
EXTRN	__imp_?qt_metacall@QDialog@@UAEHW4Call@QMetaObject@@HPAPAX@Z:PROC
EXTRN	?OnbtnLogin@frmLogin@@AAEXXZ:PROC		; frmLogin::OnbtnLogin
EXTRN	?OnbtnExit@frmLogin@@AAEXXZ:PROC		; frmLogin::OnbtnExit
CRT$XCU	SEGMENT
??staticMetaObject$initializer$@frmLogin@@2P6AXXZA@@3P6AXXZA DD FLAT:??__E?staticMetaObject@frmLogin@@2UQMetaObject@@B@@YAXXZ ; ??staticMetaObject$initializer$@frmLogin@@2P6AXXZA@@3P6AXXZA
CRT$XCU	ENDS
_DATA	SEGMENT
?staticMetaObject@frmLogin@@2UQMetaObject@@B DB 4 DUP(00H) ; frmLogin::staticMetaObject
	DD	FLAT:?qt_meta_stringdata_frmLogin@@3Uqt_meta_stringdata_frmLogin_t@@B
	DD	FLAT:?qt_meta_data_frmLogin@@3QBIB
	DD	FLAT:?qt_static_metacall@frmLogin@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
	DD	00H
	DD	00H
_DATA	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__E?staticMetaObject@frmLogin@@2UQMetaObject@@B@@YAXXZ
text$di	SEGMENT
??__E?staticMetaObject@frmLogin@@2UQMetaObject@@B@@YAXXZ PROC ; `dynamic initializer for 'frmLogin::staticMetaObject'', COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_frmlogin.cpp
; Line 83
	mov	eax, DWORD PTR __imp_?staticMetaObject@QDialog@@2UQMetaObject@@B
	mov	DWORD PTR ?staticMetaObject@frmLogin@@2UQMetaObject@@B, eax
; Line 88
	ret	0
??__E?staticMetaObject@frmLogin@@2UQMetaObject@@B@@YAXXZ ENDP ; `dynamic initializer for 'frmLogin::staticMetaObject''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_static_metacall@frmLogin@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__o$ = 8						; size = 4
__c$ = 12						; size = 4
__id$ = 16						; size = 4
__a$ = 20						; size = 4
?qt_static_metacall@frmLogin@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z PROC ; frmLogin::qt_static_metacall, COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_frmlogin.cpp
; Line 69
	push	ebp
	mov	ebp, esp
; Line 70
	cmp	DWORD PTR __c$[ebp], 0
	jne	SHORT $LN7@qt_static_
; Line 73
	mov	eax, DWORD PTR __id$[ebp]
	sub	eax, 0
	je	SHORT $LN5@qt_static_
	sub	eax, 1
	jne	SHORT $LN7@qt_static_
; Line 75
	mov	ecx, DWORD PTR __o$[ebp]
; Line 80
	pop	ebp
; Line 75
	jmp	?OnbtnExit@frmLogin@@AAEXXZ		; frmLogin::OnbtnExit
$LN5@qt_static_:
; Line 74
	mov	ecx, DWORD PTR __o$[ebp]
; Line 80
	pop	ebp
; Line 74
	jmp	?OnbtnLogin@frmLogin@@AAEXXZ		; frmLogin::OnbtnLogin
$LN7@qt_static_:
; Line 80
	pop	ebp
	ret	0
?qt_static_metacall@frmLogin@@CAXPAVQObject@@W4Call@QMetaObject@@HPAPAX@Z ENDP ; frmLogin::qt_static_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacall@frmLogin@@UAEHW4Call@QMetaObject@@HPAPAX@Z
_TEXT	SEGMENT
__c$ = 8						; size = 4
__id$ = 12						; size = 4
__a$ = 16						; size = 4
?qt_metacall@frmLogin@@UAEHW4Call@QMetaObject@@HPAPAX@Z PROC ; frmLogin::qt_metacall, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_frmlogin.cpp
; Line 106
	push	ebp
	mov	ebp, esp
	push	ebx
	push	esi
	push	edi
; Line 107
	push	DWORD PTR __a$[ebp]
	mov	edi, DWORD PTR __c$[ebp]
	mov	ebx, ecx
	push	DWORD PTR __id$[ebp]
	push	edi
	call	DWORD PTR __imp_?qt_metacall@QDialog@@UAEHW4Call@QMetaObject@@HPAPAX@Z
	mov	esi, eax
; Line 108
	test	esi, esi
	js	SHORT $LN1@qt_metacal
; Line 110
	test	edi, edi
	jne	SHORT $LN3@qt_metacal
; Line 111
	cmp	esi, 2
	jge	SHORT $LN7@qt_metacal
; Line 112
	sub	eax, edi
	je	SHORT $LN13@qt_metacal
	sub	eax, 1
	jne	SHORT $LN7@qt_metacal
	mov	ecx, ebx
	call	?OnbtnExit@frmLogin@@AAEXXZ		; frmLogin::OnbtnExit
; Line 117
	sub	esi, 2
	pop	edi
; Line 119
	mov	eax, esi
	pop	esi
	pop	ebx
; Line 120
	pop	ebp
	ret	12					; 0000000cH
; Line 112
$LN13@qt_metacal:
	mov	ecx, ebx
	call	?OnbtnLogin@frmLogin@@AAEXXZ		; frmLogin::OnbtnLogin
; Line 117
	sub	esi, 2
	pop	edi
; Line 119
	mov	eax, esi
	pop	esi
	pop	ebx
; Line 120
	pop	ebp
	ret	12					; 0000000cH
$LN3@qt_metacal:
; Line 114
	cmp	edi, 12					; 0000000cH
	jne	SHORT $LN6@qt_metacal
; Line 115
	cmp	esi, 2
	jge	SHORT $LN7@qt_metacal
; Line 116
	mov	eax, DWORD PTR __a$[ebp]
	mov	eax, DWORD PTR [eax]
	mov	DWORD PTR [eax], -1
$LN7@qt_metacal:
; Line 117
	sub	esi, 2
$LN6@qt_metacal:
; Line 119
	mov	eax, esi
$LN1@qt_metacal:
	pop	edi
	pop	esi
	pop	ebx
; Line 120
	pop	ebp
	ret	12					; 0000000cH
?qt_metacall@frmLogin@@UAEHW4Call@QMetaObject@@HPAPAX@Z ENDP ; frmLogin::qt_metacall
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qt_metacast@frmLogin@@UAEPAXPBD@Z
_TEXT	SEGMENT
__clname$ = 8						; size = 4
?qt_metacast@frmLogin@@UAEPAXPBD@Z PROC			; frmLogin::qt_metacast, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_frmlogin.cpp
; Line 98
	push	ebp
	mov	ebp, esp
	push	esi
; Line 99
	mov	esi, DWORD PTR __clname$[ebp]
	push	edi
	mov	edi, ecx
	test	esi, esi
	jne	SHORT $LN2@qt_metacas
	pop	edi
	xor	eax, eax
	pop	esi
; Line 103
	pop	ebp
	ret	4
$LN2@qt_metacas:
; Line 100
	mov	eax, OFFSET ?qt_meta_stringdata_frmLogin@@3Uqt_meta_stringdata_frmLogin_t@@B+64
	mov	ecx, esi
	npad	3
$LL5@qt_metacas:
	mov	dl, BYTE PTR [ecx]
	cmp	dl, BYTE PTR [eax]
	jne	SHORT $LN6@qt_metacas
	test	dl, dl
	je	SHORT $LN7@qt_metacas
	mov	dl, BYTE PTR [ecx+1]
	cmp	dl, BYTE PTR [eax+1]
	jne	SHORT $LN6@qt_metacas
	add	ecx, 2
	add	eax, 2
	test	dl, dl
	jne	SHORT $LL5@qt_metacas
$LN7@qt_metacas:
	xor	eax, eax
	jmp	SHORT $LN8@qt_metacas
$LN6@qt_metacas:
	sbb	eax, eax
	or	eax, 1
$LN8@qt_metacas:
	test	eax, eax
	jne	SHORT $LN3@qt_metacas
; Line 101
	mov	eax, edi
	pop	edi
	pop	esi
; Line 103
	pop	ebp
	ret	4
$LN3@qt_metacas:
; Line 102
	push	esi
	mov	ecx, edi
	call	DWORD PTR __imp_?qt_metacast@QDialog@@UAEPAXPBD@Z
	pop	edi
	pop	esi
; Line 103
	pop	ebp
	ret	4
?qt_metacast@frmLogin@@UAEPAXPBD@Z ENDP			; frmLogin::qt_metacast
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?metaObject@frmLogin@@UBEPBUQMetaObject@@XZ
_TEXT	SEGMENT
?metaObject@frmLogin@@UBEPBUQMetaObject@@XZ PROC	; frmLogin::metaObject, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\release\moc_frmlogin.cpp
; Line 94
	mov	ecx, DWORD PTR [ecx+4]
	cmp	DWORD PTR [ecx+24], 0
	je	SHORT $LN3@metaObject
	jmp	DWORD PTR __imp_?dynamicMetaObject@QObjectData@@QBEPAUQMetaObject@@XZ
$LN3@metaObject:
	mov	eax, OFFSET ?staticMetaObject@frmLogin@@2UQMetaObject@@B ; frmLogin::staticMetaObject
; Line 95
	ret	0
?metaObject@frmLogin@@UBEPBUQMetaObject@@XZ ENDP	; frmLogin::metaObject
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ
_TEXT	SEGMENT
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ PROC ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->, COMDAT
; _this$ = ecx
; File d:\qtlatest\5.12.0\msvc2017\include\qtcore\qscopedpointer.h
; Line 118
	mov	eax, DWORD PTR [ecx]
; Line 119
	ret	0
??C?$QScopedPointer@VQObjectData@@U?$QScopedPointerDeleter@VQObjectData@@@@@@QBEPAVQObjectData@@XZ ENDP ; QScopedPointer<QObjectData,QScopedPointerDeleter<QObjectData> >::operator->
_TEXT	ENDS
END
