; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24215.1 

	TITLE	E:\finalUI_316latest_canuse_300ms_DB_moreliandong\motorTest1\GeneratedFiles\qrc_motorTest1.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT
INCLUDELIB OLDNAMES

PUBLIC	?qInitResources_motorTest1@@YAHXZ		; qInitResources_motorTest1
PUBLIC	?qCleanupResources_motorTest1@@YAHXZ		; qCleanupResources_motorTest1
PUBLIC	?dummy@?A0x4c20797a@@3Uinitializer@1@A		; `anonymous namespace'::dummy
EXTRN	_atexit:PROC
_BSS	SEGMENT
?dummy@?A0x4c20797a@@3Uinitializer@1@A DB 01H DUP (?)	; `anonymous namespace'::dummy
_BSS	ENDS
CRT$XCU	SEGMENT
?dummy$initializer$@?A0x4c20797a@@3P6AXXZA DD FLAT:??__Edummy@?A0x4c20797a@@YAXXZ ; `anonymous namespace'::dummy$initializer$
CRT$XCU	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Fdummy@?A0x4c20797a@@YAXXZ
text$yd	SEGMENT
??__Fdummy@?A0x4c20797a@@YAXXZ PROC			; `anonymous namespace'::`dynamic atexit destructor for 'dummy'', COMDAT
	mov	ecx, OFFSET ?dummy@?A0x4c20797a@@3Uinitializer@1@A ; `anonymous namespace'::dummy
	jmp	??1initializer@?A0x4c20797a@@QAE@XZ	; `anonymous namespace'::initializer::~initializer
??__Fdummy@?A0x4c20797a@@YAXXZ ENDP			; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
text$yd	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??__Edummy@?A0x4c20797a@@YAXXZ
text$di	SEGMENT
??__Edummy@?A0x4c20797a@@YAXXZ PROC			; `anonymous namespace'::`dynamic initializer for 'dummy'', COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\qrc_motortest1.cpp
; Line 45
	mov	ecx, OFFSET ?dummy@?A0x4c20797a@@3Uinitializer@1@A ; `anonymous namespace'::dummy
	call	??0initializer@?A0x4c20797a@@QAE@XZ	; `anonymous namespace'::initializer::initializer
	push	OFFSET ??__Fdummy@?A0x4c20797a@@YAXXZ	; `anonymous namespace'::`dynamic atexit destructor for 'dummy''
	call	_atexit
	pop	ecx
	ret	0
??__Edummy@?A0x4c20797a@@YAXXZ ENDP			; `anonymous namespace'::`dynamic initializer for 'dummy''
text$di	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??1initializer@?A0x4c20797a@@QAE@XZ
_TEXT	SEGMENT
??1initializer@?A0x4c20797a@@QAE@XZ PROC		; `anonymous namespace'::initializer::~initializer, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\qrc_motortest1.cpp
; Line 44
	ret	0
??1initializer@?A0x4c20797a@@QAE@XZ ENDP		; `anonymous namespace'::initializer::~initializer
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ??0initializer@?A0x4c20797a@@QAE@XZ
_TEXT	SEGMENT
??0initializer@?A0x4c20797a@@QAE@XZ PROC		; `anonymous namespace'::initializer::initializer, COMDAT
; _this$ = ecx
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\qrc_motortest1.cpp
; Line 43
	mov	eax, ecx
	ret	0
??0initializer@?A0x4c20797a@@QAE@XZ ENDP		; `anonymous namespace'::initializer::initializer
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qCleanupResources_motorTest1@@YAHXZ
_TEXT	SEGMENT
?qCleanupResources_motorTest1@@YAHXZ PROC		; qCleanupResources_motorTest1, COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\qrc_motortest1.cpp
; Line 38
	mov	eax, 1
; Line 39
	ret	0
?qCleanupResources_motorTest1@@YAHXZ ENDP		; qCleanupResources_motorTest1
_TEXT	ENDS
; Function compile flags: /Ogtp
;	COMDAT ?qInitResources_motorTest1@@YAHXZ
_TEXT	SEGMENT
?qInitResources_motorTest1@@YAHXZ PROC			; qInitResources_motorTest1, COMDAT
; File e:\finalui_316latest_canuse_300ms_db_moreliandong\motortest1\generatedfiles\qrc_motortest1.cpp
; Line 32
	mov	eax, 1
; Line 33
	ret	0
?qInitResources_motorTest1@@YAHXZ ENDP			; qInitResources_motorTest1
_TEXT	ENDS
END
